server:
  address: "server:12345"
loop:
  lapse: "0m20s"
  period: "5s"
log:
  level: "info"
bet:
  name: "Santiago Lionel"
  surname: "Lorca"
  personal_id: 30904465
  birth_date: "1999-03-17"
bet_chunk:
  size: 5
  dir_data_path: "/data"
  file_name: "agency-"